services:
  test:
    image: nvidia/cuda:12.2.0-runtime-ubuntu22.04
    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  app:
    image: cli-util-dockworker
